export  const filesData = {
    id:1,
    name:'root',
    isFolder: true,
    items:[
        {   
            id:2,
            name:'node_modules',
            isFolder:true,
            items:[
                { 
                    id:3,
                    name:'react_modules_file.json',
                    isFolder:false,

                },
                { 
                    id:4,
                    name:'npm_modules_file.json',
                    isFolder:false,

                }
            ] 
        },{ 
            id:5,
            name:'src',
            isFolder:true,
            items:[
                { 
                    id:6,
                    name:'components',
                    isFolder:true,
                    items:[
                        { 
                            id:7,
                            name:'fileExplorer.jsx',
                            isFolder:false
                        }
                    ]
                },{ 
                    id:8,
                    name:'config',
                    isFolder:true,
                    items:[
                        { 
                            id:9,
                            name:'data.js',
                            isFolder:false
                        }
                    ]
                }
            ]
        },{ 
            id:10,
            name:'main.jsx',
            isFolder:false
        },
        { 
            id:11,
            name:'package-lock.json',
            isFolder:false
        },
        { 
            id:12,
            name:'package.json',
            isFolder:false
        }
    ]
}